name: hk-store-web

services:
  hk-store-web:
    image: hk-store-web
    build: .
    container_name: hk-store-web
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      - NODE_ENV=production
      - API_URL=http://192.168.1.133:3001/api

    volumes:
      - ./public:/app/public